spring.application.name=schoolmanager
server.port=${PORT:8080}

# --- CẤU HÌNH DATABASE CỦA BẠN (huyyxuan) ---
# Đã điền đúng Host, Tên DB, User và Pass
spring.datasource.url=jdbc:sqlserver://den1.mssql7.gear.host;databaseName=huyyxuan;encrypt=true;trustServerCertificate=true
spring.datasource.username=huyyxuan
spring.datasource.password=@Xuan_Huy6969

# --- CẤU HÌNH HIBERNATE ---
# Quan trọng: Đổi thành 'update' để code tự động tạo bảng (Tables) vào database mới của bạn
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false

# spring.application.name=schoolmanager
# server.port=8080
# spring.datasource.url=jdbc:sqlserver://den1.mssql7.gear.host:1433;encrypt=true;trustServerCertificate=true;databaseName=school123456
# spring.datasource.username=school123456
# spring.datasource.password=Tf1XN700~Y!T
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# spring.thymeleaf.cache=false